# Векторы в Numpy

## Векторы в Numpy и арифметика

In [14]:
# смотрим как поэлементно складываются два вектора
import numpy as np
vec1 = np.array([2, 4, 7, 2.5])
vec2 = np.array([12, 6, 3.6, 13])
print(vec1 + vec2)

# понимаем, что есть различие между списками и массивами
list1 = [2, 4, 7, 2.5]
list2 = [12, 6, 3.6, 13]
list1 + list2


[14.  10.  10.6 15.5]


[2, 4, 7, 2.5, 12, 6, 3.6, 13]

In [ ]:
# можно находить произведение векторов
vec1 = np.array([2, 4, 7, 2.5])
vec2 = np.array([12, 6, 3.6, 13])
print(vec1 * vec2)

# если вектора разной длинны, то выдается ошибка
vec1 = np.array([2, 4, 7, 2.5])
vec2 = np.array([12, 6, 3.6])
vec1 * vec2


[24.  24.  25.2 32.5]


ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [15]:
# знаем,что умножив вектор на одно число, ошибки не возникнет
vec1 = np.array([2, 4, 7, 2.5])
vec1 * 10

array([20., 40., 70., 25.])

In [17]:
# сравнение двух векторов дает нам ответ с булевыми обьектами
vec1 = np.array([2, 4, 7, 2.5])
vec2 = np.array([12, 6, 3.6, 13])
vec1 > vec2

array([False, False,  True, False])

In [19]:
# каждый элемент сравнивается с одним числом,
# результат аналогичен предыдуще строке кода
vec1 = np.array([12, 6, 3.6, 13])
vec1 <= 20

array([ True,  True,  True,  True])

### Задание 8.2

In [ ]:
# вектора с разной длинной не попасть под сравнение 
vec1 = np.array([12, 45, 34, 46])
vec2 = np.array([12, 5, 75])
vec1 >= vec2

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

## Продвинутые операции с векторами

In [23]:
# вычисляем длинну вектора 
vec = np.array([3, 4])
length = np.sqrt(sum(vec ** 2))
print(length)

# используем быстрый способ нахождения длинны вектора из библиотеки linalg
# библиотеки Numpy
length = np.linalg.norm(vec)
length

5.0


5.0

In [26]:
# находим расстояние между векторами
vec1 = np.array([0, 3, 5])
vec2 = np.array([12, 4, 7])
distance = np.sqrt(np.sum((vec1 - vec2) ** 2))
print(distance)

# более лаконичный способ с использованием модуля .linalg, 
# тоже находит расстояние
distance = np.linalg.norm(vec1 - vec2)
distance

12.206555615733702


12.206555615733702

In [30]:
# находим скальярное произведение, для того чтобы узнать угол
vec1 = np.arange(1, 6)
vec2 = np.linspace(10, 20, 5)
scalar_product = np.sum(vec1 * vec2)
print(scalar_product)

# вышезаписанный код можно упростить при помощи встроенной функции .dot
scalar_product = np.dot(vec1, vec2)
scalar_product

250.0


250.0

## Задание 8.6

In [37]:
a = np.array([23, 34,27])
b = np.array([-54, 1, 46])
c = np.array([46, 68, 54])

# находим длинну векторов длятого чтобы использовать эту информацию 
# при определении сонаправленности векторов
a_length = np.linalg.norm(a)
b_length = np.linalg.norm(b)
c_length = np.linalg.norm(c)

# длинна суммы веторов позволяет определить сонаправленность векторов
ab_sum = np.linalg.norm(a + b)
ac_sum = np.linalg.norm(a + c)
bc_sum = np.linalg.norm(b + c)

# определяем сонаправленные вектора
print(a_length + b_length == ab_sum)
print(a_length + c_length == ac_sum)
print(b_length + c_length == bc_sum)

# рисую много точек для удобного прочтенния вывода
print('*' * 60)

# находим, какок из расстояния двух векторв больше 100
print(np.linalg.norm(a - b) > 100)
print(np.linalg.norm(a - c) > 100)
print(np.linalg.norm(b - c) > 100)

print('*' * 60)

# .dot более лаконичный способ нахождения скалярного произведения
ab_scalar = np.dot(a, b)
ac_scalar = np.dot(a, c)
bc_scalar = np.dot(b, c)
print(ab_scalar, ac_scalar, bc_scalar)

False
True
False
************************************************************
False
False
True
************************************************************
34 4828 68


## Базовые статистические функции для векторов

### np.min(), np.max()

In [40]:
# создали одномерный массив
vec = np.array([2, 7, 18, 28, 18, 1, 8, 4])
# находим минимум и максимум вектора
print(np.min(vec))
np.max(vec)

1


28

### .mean()

In [42]:
# одномерный массив нужен для того чтобы в нем найти среднее значение
vec = np.array([2, 7, 18, 27, 18, 1, 8, 4])
# узнаем среднее значение
vec.mean()

10.625