# Случайные числа в Numpy

### Генерация float

#### .random.rand()

In [18]:
# получаем достп к библиотеке Numpy
import numpy as np
# получаем случайное число от 0 до 1
print(np.random.rand())

# разделительная черта нужна для читабельности кода
print('*' * 60)

# интересный способ получения случайного числа от 0 до 100
print(np.random.rand() * 100)

print('*' * 60)

# генерирую случайные числа в виде одномерного масива
# с заданным числом элементов
print(np.random.rand(5))

print('*' * 60)

# создание двумерного масива
print(np.random.rand(2, 3))

print('*' * 60)

# смотрим на то как выглядит многомерный масив
np.random.rand(2, 3, 3, 4, 5)

0.4301455108114842
************************************************************
62.22223652479323
************************************************************
[0.92225594 0.27504394 0.15891063 0.39499812 0.41728425]
************************************************************
[[0.96742353 0.52480719 0.78702113]
 [0.85575573 0.28310095 0.63613133]]
************************************************************


array([[[[[6.43364547e-01, 4.68475283e-01, 1.57088479e-01,
           9.22934287e-01, 5.68705025e-01],
          [2.75626227e-01, 3.47913963e-01, 8.45492028e-01,
           4.76946893e-01, 6.16663498e-01],
          [3.90279679e-01, 5.71103259e-01, 4.67775072e-02,
           9.89304426e-01, 2.26953441e-01],
          [5.87903045e-01, 8.04401420e-01, 8.30414972e-01,
           2.93008551e-01, 2.11641345e-01]],

         [[5.03931698e-01, 1.41649875e-01, 4.37925735e-01,
           5.37051664e-01, 7.55209220e-01],
          [7.33155107e-01, 4.32942099e-01, 1.27569115e-01,
           5.83336582e-01, 3.00833788e-01],
          [4.11760291e-01, 4.60922862e-01, 7.60008615e-01,
           4.32621777e-01, 2.91150389e-01],
          [7.62149343e-01, 9.42470891e-01, 5.89744212e-01,
           6.04975672e-01, 7.09921629e-01]],

         [[6.31277071e-02, 8.00658897e-02, 5.88228655e-01,
           1.54910071e-01, 2.52814801e-01],
          [5.94604202e-02, 7.12033108e-01, 7.04828503e-01,
          

#### .random.sample()

In [27]:
# передаем кортеж в функцию
shape = (2, 3)
# запоминаем, что кортеж не может быть предан в виде аргумента
np.random.rand(shape)


TypeError: 'tuple' object cannot be interpreted as an integer

In [28]:
# распаковка позволяет передать кортеж в аргумент
print(np.random.rand(*shape))

# раздельительная черта из звездочек дужна чтобы быстро читать и понимаьт код
print('*' * 60)

# находим результат и получаем способность внести в качестве аргумента 
# кортеж
np.random.sample(shape)

[[0.17982565 0.28266373 0.75498426]
 [0.10021419 0.95102238 0.36080601]]
************************************************************


array([[0.84152758, 0.31101766, 0.72957173],
       [0.4413985 , 0.93347949, 0.04586468]])

#### .random.uniform()

In [36]:
# такая запись даст нам одно число в диапозоне от 0 до 1
print(np.random.uniform())

# разделяем вывод для лучшей читабельности
print('*' * 60)

# задаем новые ганицы диапозона
print(np.random.uniform(-30, 50))

print('*' * 60)

# изучаем метод, который позволяет устанавливать верхнюю границу,
# нижнюю границу, количество элементов в массиве
print(np.random.uniform(0.5, 0.75, size=5))

print('*' * 60)

# в аргументации можно указать размерность в виде кортежа
print(np.random.uniform(-1000, 500, size=(2, 3)))


0.2572132965254462
************************************************************
-27.5715983875278
************************************************************
[0.73824274 0.63257956 0.73743835 0.71659042 0.62092939]
************************************************************
[[-900.37541161 -303.89624408  -80.53704793]
 [ 336.26790225 -143.28652603 -212.67788603]]


## Генерация int

### .random.randint()

In [39]:
# такая запись будет давать случайные числа от нуля до аргумента - 1
# и это при условии, что верхняя граница не указанна
print(np.random.randint(4, size=(2, 3)))

print('*' * 60)

# при указании и нижней и верхней границы, случайные числа будут
# выбираться из этого диапозона
print(np.random.randint(6, 12, size=(3, 3)))

[[0 0 0]
 [1 1 0]]
************************************************************
[[ 7  9  8]
 [11  7  9]
 [10 11  8]]


## Генерация выборок

### .random.shuffle()

In [ ]:
# создаем одномерный массив
arr = np.arange(6)
# перемешиваем одномерный массив с помощью метода .shuffle(), 
# библиотеки .random
np.random.shuffle(arr)
arr

array([2, 4, 3, 0, 1, 5])

### .random.permutation()

In [ ]:
playlist = ["The Beatles", "Pink Floyd", "ACDC", "Deep Purple"]
# в отличии от .shuffle перемешанный масив может поместиться в обьекте
shuffeled = np.random.permutation(playlist)
# отмечаем, что основной список не изменился
print(playlist)
print(shuffeled)

# одновременно создаем массив из чесел, идущих по возастанию,
# и перемешиваем его 
np.random.permutation(10)

['The Beatles', 'Pink Floyd', 'ACDC', 'Deep Purple']
['Deep Purple' 'Pink Floyd' 'ACDC' 'The Beatles']


array([2, 3, 4, 7, 1, 9, 8, 5, 6, 0])

### .random.chooice()

In [52]:
workers = ['Ivan', 'Nikita', 'Maria', 'John', 'Kate']

# сохраняем  в переменную заданное количество случайных чисел
choice = np.random.choice(workers, size= 2, replace=False)
print(choice)

# если в аргументе длинна больше чем список, возникнет ощибка
choice = np.random.choice(workers, size=10, replace=False)
choice

['Nikita' 'John']


ValueError: Cannot take a larger sample than population when 'replace=False'

In [68]:
workers = ['Ivan', 'Nikita', 'Maria', 'John', 'Kate']
# 
choice = np.random.choice([1, 2, 3, 4, 5, 6, 7], size=10,)
choice

array([6, 3, 5, 6, 3, 3, 4, 5, 5, 5])

## seed генератора случайных чисел

### .random.seed(<np.uint32>)

In [86]:
# задем значение seed к котрому будет привязана псевдослучайная
# генерация цифр
np.random.seed(23)
np.random.randint(10, size=(3, 4))

array([[3, 6, 8, 9],
       [6, 8, 7, 9],
       [3, 6, 1, 2]])

In [79]:
# смотрим на повторимость случайной генерации цифр
np.random.seed(100)
print(np.random.randint(10, size=3))
print(np.random.randint(10, size=3))
print(np.random.randint(10, size=3))


[8 8 3]
[7 7 0]
[4 2 5]


## Задание 9.6

In [7]:
# используем библиотеку Numpy
import numpy as np
# работаем с генерациями при seed равным 2021
np.random.seed(2021)
# пишем быстрый способ напечатать случайное число от 0 до 1
simple = np.random.rand()
# находим 120 случайных чисел в заданном диапозоне
randoms = np.random.uniform(-150, 2021, size=120)
# получаем целые случайные числа
table = np.random.randint(1, 101, size=(3, 2))
# использую быстрый способ создания последовательности чисел
even = np.arange(17)[::2]
# убираем первый элемент
even = even[1::]
# закрепляем знания о работе с функцией .copy()
mix = even.copy()
# закрепляем знания о работе метода .shuffle()
np.random.shuffle(mix)
# закрепляем знания о работе функции .choice()
select = np.random.choice(even, size=3, replace=False)
# в отличии от .shuffle(), .permutation() может быть возвращена
triplet = np.random.permutation(select)
print(simple, randoms, table, even, mix, select, triplet, sep='\n')

0.6059782788074047
[ 1.44214488e+03  1.51654277e+02  5.28813265e+02  2.01501516e+03
  1.28240517e+02  2.38594033e+02  1.48460111e+03  1.28755048e+03
  1.55273730e+03  6.03577336e+01 -2.28417401e+01  1.93936169e+03
  1.18854621e+03  3.80736459e+01  1.06852230e+03  1.18847514e+03
  1.94250320e+03  1.09681462e+03  6.55790201e+02  8.31607324e+02
  2.88216888e+02  1.08596141e+03  2.73553360e+02  1.11722142e+03
  8.84076551e+02  9.74175063e+02  1.63694713e+03  1.43966053e+03
 -7.88273550e-02  1.30919192e+03  1.24700551e+03  1.64761920e+03
  2.93903055e+02  1.19056852e+03  1.19102890e+03  5.03619976e+02
  1.74254881e+03  1.13013901e+03  1.98142287e+03  8.10086179e+02
  1.24235695e+02  9.54671885e+02  7.87407805e+02  1.83850479e+03
  1.38927296e+03  1.78361285e+03  1.12847065e+03  1.23255777e+03
  5.92935602e+02  1.63845066e+03  5.12482326e+02  5.17676863e+02
  2.87071500e+02  4.25673103e+02  1.26315547e+03  1.85668749e+02
  6.93866612e+02  1.25597031e+03  1.69165738e+03 -1.14109610e+01
  7.49