# Knowledge solidifying

In [1]:
import numpy as np
num = np.int16('-65536')
num

0

## Задание 10.6

Напишите функцию get_chess(a), которая принимает на вход длину стороны квадрата a и возвращает двумерный массив формы (a, a), заполненный 0 и 1 в шахматном порядке. В левом верхнем углу всегда должен быть ноль.

Примечание. воспользуйтесь функцией np.zeros, а затем с помощью срезов без циклов задайте необходимым элементам значение 1.

В Python для получения каждого второго элемента используется срез [::2]. Подумайте, как грамотно применить этот принцип к двумерному массиву.

In [2]:
def get_chess(side):
    # если число четное то, метод описанный в блоке else не сработает
    if side % 2 == 0:
        # узнаем количество элементов
        arr = np.zeros((side, side))
        arr.size
        # выствляем нужную нам последовательность цифр в одномерном массиве 
        arr = np.zeros(arr.size)
        arr[::2] = 1
        # воссоздаю заного мнономерный массив
        arr.shape = ((side, side))
        # в каждой нечетной строке выствляю порядк цифр 0 1 0 1 и т.д.
        arr[::2, :] = 1
        arr[::2, ::2] = 0
        # обязательное возвращене массива 
        return arr
    # иначе делаем так
    else:
        # будем извлекать информацию о количестве элементов
        arr = np.zeros((side, side))
        # будем преобразовывать многомерный масив в одномерный на основании 
        # информации о количестве элементов
        arr.size
        # делаем каждый второй элемент 1
        arr = np.zeros(arr.size)
        # сначала превратили все в 1
        arr[:] = 1
        # а потом делаем каждый второй элемент 0
        arr[::2] = 0
        arr.shape = ((side, side))
        # пересоздаем масив для вывода из функции
        #arr.shape = (side, side)
        # возвращаем резултат
        return arr

# получается красиво
get_chess(10)

array([[0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0.]])

## Задание 10.7

Вы разрабатываете приложение для прослушивания музыки. Конечно же, там будет доступна функция перемешивания плейлиста. Пользователю может настолько понравиться перемешанная версия плейлиста, что он захочет сохранить его копию. Однако вы не хотите хранить в памяти новую версию плейлиста, а просто хотите сохранять тот seed, с которым он был сгенерирован.

Для этого напишите функцию shuffle_seed(array), которая принимает на вход массив из чисел, генерирует случайное число для seed в диапазоне от 0 до 2**32 - 1 (включительно) и возвращает кортеж: перемешанный с данным seed массив (исходный массив должен оставаться без изменений), а также seed, с которым этот массив был получен.



In [3]:
# создаем функцию
def shuffle_seed(array):
    # создаем случайное целое число, которое будет сидом
    gen_numb = np.int64(np.random.rand() * (2 ** 32 -1))
    np.random.seed(gen_numb)
    # перемешиваем масив
    np.random.shuffle(array)
    
    # возвращаем через запятую массив и сид
    return array, gen_numb

shuffle_seed(np.array([1, 2, 3, 4, 5, 6, 7]))
    


(array([2, 6, 7, 1, 5, 4, 3]), 1009165886)

In [4]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
np.random.shuffle(arr)
arr

array([2, 3, 1, 5, 6, 4, 7])

## Задание 10.8

Напишите функцию min_max_dist(*vectors), которая принимает на вход неограниченное число векторов через запятую. Гарантируется, что все векторы, которые передаются, одинаковой длины.

Функция возвращает минимальное и максимальное расстояние между векторами в виде кортежа.

In [5]:
vec1 = np.array([1,2,3])
vec2 = np.array([4,5,6])
vec3 = np.array([7, 8, 9])

#min_max_dist(vec1, vec2, vec3)

a = 1
b = 2
c = 3
d = 4
example = vec1, vec2, vec3

def ex_func(*example):
    
    #np.linalg.norm(vec1 - vec2 - vec3)

    return example

ex_func(*example)

(array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]))

In [10]:
import numpy as np


vec1 = np.array([1, 2, 3])
vec2 = np.array([4, 5, 6])
vec3 = np.array([7, 8, 9])


# инициируем функцию
def min_max_dist(*vectors):
    # создаем список из масивов, для обработки каждого элемента
    # с каждым элементом
    array_list = []
    # для каждого элемента найдем найдем расстояние между веторами из переменной 
    # vectors
    for elem in vectors:
        array_list.append(elem)
    # создаю список для хранения в нем расстояний
    dist_list = []
    # проверяем работу по нахожденю расстояний 
    for elem in array_list:
        for second_elem in vectors:
            distance = np.linalg.norm(elem - second_elem)
            dist_list.append(distance)
    # создаю список без нулей для красоты и для удобства выбора минимального и
    # максимального значения
    result_list = []
    for elem in dist_list:
        if elem == 0.0:
            continue
        else:
            result_list.append(elem)
    return min(result_list), max(result_list)
        
    
min_max_dist(vec1, vec2, vec3)        
        

(5.196152422706632, 10.392304845413264)

## Задание 10.9

Напишите функцию any_normal, которая принимает на вход неограниченное число векторов через запятую. Гарантируется, что все векторы, которые передаются, одинаковой длины.

Функция возвращает True, если есть хотя бы одна пара перпендикулярных векторов. Иначе возвращает False.

In [13]:
import numpy as np


vec1 = np.array([2, 1])
vec2 = np.array([-1, 2])
vec3 = np.array([3,4])

# инициализирую функцию
def any_normal(*vectors):
    # создаю список из элементов переменной vectors, для того чтобы итерировать
    elem_list = []
    # заполняю пустой список
    for elem in vectors:
        elem_list.append(elem)
    # создаю пустой список, который будет заполнен скалярными произведениями
    # пар векторов    
    scalar_list = []
    # заполняю список скалярными произведениями
    for elem in elem_list:
        for second_elem in vectors:
            scalar_product = np.dot(elem, second_elem)
            scalar_list.append(scalar_product)
    # ищем условие для поиска перпендиклярных векторов
    if 0 in scalar_list:
        return True
    else:
        return False

any_normal(vec1, vec2, vec3)    



True

## Задание 10.10

Напишите функцию get_loto(num), генерирующую трёхмерный массив случайных целых чисел от 1 до 100 (включительно). Это поля для игры в лото.

Трёхмерный массив должен состоять из таблиц чисел формы 5х5, то есть итоговая форма — (num, 5, 5).

Функция возвращает полученный массив.

In [ ]:
# скачаиваем библиотеку Numpy
import numpy as np


# инициализируем функцию
def get_loto(num):
    # такое обращение позволяет создать масиивы из случайных целых чисел
    arr = np.random.randint(1, 100, size=(num, 5, 5))
    # возвращаем массив
    return arr

get_loto(4).shape
    

(4, 5, 5)

## Задание 10.11

Напишите функцию get_unique_loto(num). Она так же, как и функция в задании 49.9.10, генерирует num полей для игры в лото, однако теперь на каждом поле 5х5 числа не могут повторяться.

Функция также должна возвращать массив формы num x 5 x 5.

In [140]:
# обязательный вызов библиотеки numpy
import numpy as np


# инициализирую функцию
def get_unique_loto(num):
    # будем изменять элементы пустого масива на уникальные поля
    zeros_array = np.zeros((num, 5, 5))
    # пройдемся циклом по этоиу масиву и заменим элементы при помощи 
    # np.random.choice() и .reshape()
    for i, elem in enumerate(zeros_array):
        # раскладываем масив с числами от 1 до 100
        num_array = np.arange(1, 101)
        # выбираем 25 чисел и меняем форму на (5, 5)
        unique_choice = np.random.choice(num_array, size=25, replace=False)
        choice_reshape = unique_choice.reshape(5, 5)
        # теперь заполняем массив из нулей 
        zeros_array[i] = choice_reshape
        
    return zeros_array 

print(get_unique_loto(4))

        

[[[55. 49. 96. 46. 83.]
  [85. 20. 57. 87. 41.]
  [68. 26. 29. 33. 39.]
  [35. 27. 44. 82. 92.]
  [78. 56. 31. 62. 91.]]

 [[72. 56. 88. 60. 29.]
  [68. 36.  8.  2. 40.]
  [96.  4. 26. 65. 71.]
  [45. 64. 25. 16. 67.]
  [69. 12. 99. 15. 50.]]

 [[30. 49.  5. 85. 23.]
  [99. 12. 83. 57. 82.]
  [66. 96. 97. 89. 72.]
  [80. 13. 88. 87. 51.]
  [27. 76. 60. 62. 22.]]

 [[77. 96. 81. 31. 78.]
  [67. 76. 15. 50.  4.]
  [54. 94. 49. 83. 95.]
  [69. 80. 66. 65. 34.]
  [85. 43. 71. 30. 21.]]]


In [ ]:
# импортирую библиотеку Numpy для работы
import numpy as np


# создаю функцию, которая будет выдавать поля без повторяющихся элементов
def get_unique_loto(num):
    # пустой массив будем пополнять элементами, полями
    # исходный масив должен иметь такое количество измерений
    # сколько будет введено в аргументе функциии
    arr = np.zeros((num, 5, 5))
    # создаем массив с заданным в синтаксисе аргументом
    unique_array = np.random.randint(1, 100, size=(num, 5, 5))
    # чтобы воссоздать элементы в новом массиве создаю массив
    # содержащий числа от 1 до 100
    arr_num = np.arange(1, 101)
  
    # создаю цикл для обработки и создания уникального масива
    for i, elem in enumerate(unique_array):
        # создаю условие проверяющее на уникальность
        if len(set(elem.flatten())) == len(elem.flatten()):
            arr[i] = elem
        # иначе подставляем массив из уникальных чисел, 
        # преобразованный в поле 5 х 5
        else:
            choice_arr = np.random.choice(arr_num, size=25, replace=False)
            choice_shape = choice_arr.reshape(5, 5)
            arr[i] = choice_shape
            
    # возвращаем унмкальную функцию
    return arr

# проверяем работу функции
get_unique_loto(3)       
            
    

array([[[99., 91., 14., 90., 61.],
        [28., 10.,  7., 85., 79.],
        [ 5., 53., 64., 95., 20.],
        [58., 56., 41., 32., 24.],
        [55., 82., 83., 36., 84.]],

       [[96., 81., 17.,  2., 73.],
        [71., 29., 65.,  1., 28.],
        [14., 64., 41.,  7., 60.],
        [25., 63., 50., 11., 39.],
        [87., 75., 12., 45., 91.]],

       [[25., 14., 26.,  7., 85.],
        [59.,  8., 42., 11., 13.],
        [49., 29., 53., 45., 31.],
        [78., 38., 88., 30., 51.],
        [64.,  6., 69., 40., 61.]]])