## Масивы в numpy

### Создание масива из списка

In [1]:
# Ипользуем библиотеку numpy
import numpy as np
# создаем массив при помощи np.array()
arr = np.array([1, 2, 3, 4, 5, 6])
# печатаем массив
arr

array([1, 2, 3, 4, 5, 6])

In [6]:
# функция возвращает обьект типа ndarray, n-dimensional array
print(type(arr))

<class 'numpy.ndarray'>


In [ ]:
# создаем двумерный массив
nd_arr = np.array([[1, 2, 3, 4, 5],
                  [10, 11, 12, 13, 14],
                  [111, 112,113,114,115]
                  ])
nd_arr

array([[  1,   2,   3,   4,   5],
       [ 10,  11,  12,  13,  14],
       [111, 112, 113, 114, 115]])

### Типы данных в массиве

In [5]:
# проверяем какой тип данных модуль numpy создает по умолчанию
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int64')

In [ ]:
# задаем тип данных массива по умолчанию
arr = np.array([1, 2, 3, 4, 5], dtype=np.int8)
# видим что, без вункции print выводится наш массив
arr

array([1, 2, 3, 4, 5], dtype=int8)

In [ ]:
# результат будет с ошибкой, потому что мы выходим за диапозон
# допустимых значений
arr[2] = 1500
arr

/tmp/ipykernel_4882/950604027.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 1500 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  arr[2] = 1500


array([  1,   2, -36,   4,   5], dtype=int8)

In [ ]:
# для чисел типа float необходимо сначала привести к правельному типу данных
arr[2] = 125.2
arr

array([  1,   2, 125,   4,   5], dtype=int8)

In [8]:
# строка с цифромым значением будет приведена к заданному типу данных int8
arr[2] = '29'
arr

array([ 1,  2, 29,  4,  5,  6])

In [7]:
# видим, что если строка не цифра, то будет ошибка
arr[2] = 'boss'
arr

ValueError: invalid literal for int() with base 10: 'boss'

In [ ]:
# меняем тип данных на числа с плавающей точкой
arr = np.float128(arr)
arr

array([ 1.,  2., 29.,  4.,  5.,  6.], dtype=float128)

In [ ]:
# видим что в тип данных с меньшей емкостью не будут храниться числа,
# которые требуют больше памяти
arr = np.array([13456, 1845, -4563, 100, 2000], dtype=np.int32)

print(arr)
arr = np.int8(arr)
# все числа кроме ста записались неверно
arr

[13456  1845 -4563   100  2000]


array([-112,   53,   45,  100,  -48], dtype=int8)

### Свойство numpy-массивов

In [ ]:
# сдоздаем одномерный и двухмерный массив для дальнейшей работы
arr = np.array([1, 2, 3, 4, 5], dtype=np.int8)
nd_arr = np.array([[14, 26, 19],
                  [45, 67,12], 
                  [98, 78, 56]
                  ], dtype=np.int16)

array([1, 2, 3, 4, 5], dtype=int8)

#### атрибут .ndim

In [18]:
# запоминаем, что с помощью .ndim можно узнать размернось массива
print(arr.ndim)
nd_arr.ndim

1


2

#### атрибут .size

In [20]:
# узнаем информацмю об общем количестве элементов
print(arr.size)
nd_arr.size


5


9

#### атрибут .shape

In [21]:
# смотрим как выводиться форма numpy-массива в виде кортежа
print(arr.shape)
nd_arr.shape

(5,)


(3, 3)

#### атрибут .itemsize

In [ ]:
# узнаем количество занимаемого места в памяти в байтах
print(arr.itemsize) 
nd_arr.itemsize

1


2

### Заполнение новых массивов

#### np.zeros()

In [25]:
# создаем массив из нулей, заданной формы, для дальнейшего заполнения
zerose_1d = np.zeros(5)
zerose_1d

array([0., 0., 0., 0., 0.])

In [ ]:
# создаем трехмерный numpy-массив с заданной формы и типом
zerose_3d = np.zeros((3, 4, 3), dtype=np.float32)
print(zerose_3d.shape) 

(3, 4, 3)


#### np.arrange([start,], stop, [step,], dtype=None)

In [38]:
# видим, что функция .arrange может выводить список чисел с типом данных float
print(np.arange(5))
print(np.arange(2.5, 5))
# функция .arange может передивигаться с шагом 0.5
print(np.arange(2.5, 5, 0.5))
# удостоверились, что np.arange создает массив с типом данных float
np.arange(2.5, 5, 0.5, dtype=np.float16)

[0 1 2 3 4]
[2.5 3.5 4.5]
[2.5 3.  3.5 4.  4.5]


array([2.5, 3. , 3.5, 4. , 4.5], dtype=float16)

#### np.linspace(start, stop, num=50, endpoint=True, retstep=True, dtype=None)

In [ ]:
# смотрим как работает функция linspace ,которая более предпочтетельнее
# при работе с дробными числами
arr = np.linspace(1, 2, 10)
arr

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

In [40]:
# включаем последнююю цивру в массив
arr = np.linspace(1, 2, 10, endpoint=False)
arr

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

In [8]:
# Узнаем как работает возвращаемость размера шага массива
arr, step = np.linspace(1, 2, 10, endpoint=True, retstep=True)
# запоминаем, что вторым значением выводиться шаг масива, при redstep=True
print(step)

0.1111111111111111


In [9]:
# смотрим, что шаг становиться другим если поменять значение аргумент endpoint
arr, step = np.linspace(1, 2, 10, endpoint=False, retstep=True)
print(step)

0.1


In [14]:
# узнаем какой шаг в диапозоне от -6 до 21, состоящего из 60 элементов
arr_task, step = np.linspace(-6, 21, 60, endpoint=True, retstep=True)
print(round(step, 2))

0.46


In [15]:
# узнаем какой шаг в диапозоне от -6 до 21, где число 21 не вкючен в массив 
arr_task_second, step = np.linspace(-6, 21, 60, endpoint=False, retstep=True)
print(round(step, 2))

0.45
