## Действия с массивами


### Изменения формы массива

In [11]:
# обязательный импорт модуля numpy
import numpy as np
# создаем массив
arr = np.arange(8)
# проверяем результат
arr


array([0, 1, 2, 3, 4, 5, 6, 7])

#### .shape()

In [3]:
# изменяем форму массива присвоив функции .shape желаемую форму
arr.shape = (2, 4)
# проверяем как изменилась форма
arr

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

#### .reshape()

In [6]:
# при помощи данной записи мы можем сохранить в распоряжении массив до 
# изменеия и новый массив
arr = np.arange(8)
print(arr)
new_arr = arr.reshape(2, 4)
new_arr


[0 1 2 3 4 5 6 7]


array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [8]:
# изменяем исходный массив по столбцам при помощи атрибута 'F'
new_arr = arr.reshape(2, 4, order='F')
new_arr

array([[0, 2, 4, 6],
       [1, 3, 5, 7]])

#### .transpose()

In [13]:
# создаем массив
arr = np.arange(8)
arr
# тренирумеся в создании двумерного массива и одномерного
arr.shape = (2, 4)
arr


array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [ ]:
# создаем массив в котором строки и столбцы поменялись местами
arr_trans = arr.transpose()
arr_trans

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

In [16]:
# транспонирование ономерного массива не происходит
arr = np.arange(3)
print(arr.shape)
arr_trans = arr.transpose()
print(arr_trans.shape)

(3,)
(3,)


### Индексы и  срезы в массивах

In [58]:
# создаем массив для взятия элемента по индексу
arr = np.linspace(1, 2, 6)
arr
# берем элемент по индексу 
print(arr[2])
# берем срез массива
print(arr[2:4])
# печатаем массив наоборот
print(arr[::-1])

1.4
[1.4 1.6]
[2.  1.8 1.6 1.4 1.2 1. ]


In [29]:
# создаем двумерный массив из одномерного
arr_new = np.linspace(0, 6, 12, endpoint=False).reshape(3, 4)
arr_new 

array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5],
       [4. , 4.5, 5. , 5.5]])

In [33]:
# такая запись помогает взять элемент как и в случае со списком из списков
print(arr_new[1][2])
# numpy позволяет брать элементы более красивым способом
print(arr_new[1, 2])
# в получении элементов можно использовать срезы
print(arr_new[:2, 3])
# в получении элементов по индексу можно использовать срезы
print(arr_new[1:, 2:4])
# так мы берем срезы элементов двумерного массива
print(arr_new[:, 2:4])
# так мы получаем все элементы двумерного массива целиком
print(arr_new[:2])

3.0
3.0
[1.5 3.5]
[[3.  3.5]
 [5.  5.5]]
[[1.  1.5]
 [3.  3.5]
 [5.  5.5]]
[[0.  0.5 1.  1.5]
 [2.  2.5 3.  3.5]]


In [23]:
arr = np.linspace(1, 7, 10)
print(len(arr))

10


In [18]:
# Введите свое решение ниже
import numpy as np

mystery = np.array([[-13586,  15203,  28445, -27117,  -1781, -17182, -18049],
       [ 25936, -30968,  -1297,  -4593,   6451,  15790,   7181],
       [ 13348,  28049,  28655,  -6012,  21762,  25397,   8225],
       [ 13240,   7994,  32592,  20149,  13754,  11795,   -564],
       [-21725,  -8681,  30305,  22260, -17918,  12578,  29943],
       [-16841, -25392, -17278,  11740,   5916,    -47, -32037]],
      dtype=np.int16)

# сохраняем элемент из пятой строки и третьего столбца
elem_5_3 = mystery[4, 2]
print(elem_5_3)
# сохраняем элемент из последней строки последнего элемента
last = mystery[len(mystery) - 1, len(mystery[0])- 1]
print(last)
# выделяем четветую строку
line_4 = mystery[3]
print(line_4)
print()
# выделяем предпоследний столбец
col_2 = mystery[:, len(mystery[0]) - 2]
print(col_2)
print()
# из строк 2-4 получаем столбцы 3-5
part = mystery[1:4, 2:5]
print(part)
print()
# получаем последний столбец перевернутым
rev = mystery[:len(mystery), len(mystery[0]) - 1]
rev = rev[::-1]
print(rev)
print()
# транспонируем массив
trans = mystery.transpose()
print(trans)

30305
-32037
[13240  7994 32592 20149 13754 11795  -564]

[-17182  15790  25397  11795  12578    -47]

[[-1297 -4593  6451]
 [28655 -6012 21762]
 [32592 20149 13754]]

[-32037  29943   -564   8225   7181 -18049]

[[-13586  25936  13348  13240 -21725 -16841]
 [ 15203 -30968  28049   7994  -8681 -25392]
 [ 28445  -1297  28655  32592  30305 -17278]
 [-27117  -4593  -6012  20149  22260  11740]
 [ -1781   6451  21762  13754 -17918   5916]
 [-17182  15790  25397  11795  12578    -47]
 [-18049   7181   8225   -564  29943 -32037]]


### Сортировка одномерных массивов

In [21]:
# создаю одномерный массив для дальнейшей обработки
arr = np.array([8, 7, 6, 5, 4, 3, 2, 1])
# складываем отсортированный массив в переменную
new_arr = np.sort(arr)
print(arr)
print(new_arr)


[8 7 6 5 4 3 2 1]
[1 2 3 4 5 6 7 8]


In [24]:
# создаю массив для того, чтбы покзать что можно сортировать еще одним способом
arr = np.array([8, 7, 6, 5, 4, 3, 2, 1])
# при такой записи возвращается обьект типа None
print(arr.sort())
# видим, что сама функция возвращается осортиррованной
print(arr)

None
[1 2 3 4 5 6 7 8]


### Работа с пропущенными двнными

In [12]:
# создадим массив и посмотрим как обрабатывать пропущенные данные
data = np.array([4, 9, -4, 10])
# узнаем способности функции np.sqrt
roots = np.sqrt(data)
# видим, что в выводе корень из -4 является обьекту nan
roots

/tmp/ipykernel_5944/3237191913.py:4: RuntimeWarning: invalid value encountered in sqrt
  roots = np.sqrt(data)


array([2.        , 3.        ,        nan, 3.16227766])

In [6]:
# вспоминаем, что обьект None, это обьект типа Nonetype,
# а обьект nan - это отельный представитель класса float
print(type(None))
print(type(np.nan))

<class 'NoneType'>
<class 'float'>


In [10]:
# запоминаем, что обьекты None могут быть равны друг другу, а 
# обьекты np.nan нет
print(None == None)
print(np.nan == np.nan)
# хотя при операторе is обькеты np.nan равны
print(None is None)
print(np.nan is np.nan)
print(None is np.nan)

True
False
True
True
False


In [ ]:
# видим, что расчет не полуиться так как присутствует обьект np.nan
sum(roots)

nan

#### np.isnan(<массив>)

In [16]:
# получаем массив из булевых значение в которых булевый обьект True 
# является обьектом типа np.nan
np.isnan(roots)

array([False, False,  True, False])

In [7]:
# выводим обьект типа np.nan для дальнейшего замещения на ноль
roots[np.isnan(roots)]

array([nan])

In [5]:
# замещаем обьект на ноль
roots[np.isnan(roots)] = 0
roots

array([2.        , 3.        , 0.        , 3.16227766])

In [6]:
sum(roots)

8.16227766016838

In [7]:
print(np.isnan(np.nan))

True


In [46]:
mystery = np.array([ 12279., -26024.,  28745.,  np.nan,  31244.,  -2365.,  -6974.,
        -9212., np.nan, -17722.,  16132.,  25933.,  np.nan, -16431.,
        29810.], dtype=np.float32)

# узнаю сколько обьектов nan существует в масиве mystery
nans_index = np.isnan(mystery)
nans_index

count = 0
for a in nans_index:
    if a == True:
        count += 1
n_nan = count
n_nan 

mystery_new = mystery.copy()
# создаем новый масив в котором обьекты типа np.nan замещены на 0
mystery_new[np.isnan(mystery_new)] = 0
mystery_new


# меняю тип данных
mystery_int = np.int32(mystery)
mystery_int

# сортирую по возрастанию
array = np.sort(mystery)
array

# создаю двуменый массив, который заполняется по столбцам при помощи метода
# .reshape()
table = array.reshape(5, 3, order='F')
table

# сохраняю в переменнуб col только нужный мне срез
col = table[:5, 1]
print(col)


[-2365. 12279. 16132. 25933. 28745.]


/tmp/ipykernel_5944/1457285775.py:23: RuntimeWarning: invalid value encountered in cast
  mystery_int = np.int32(mystery)
